### ISSUE TITLE
bot exit after sometime with code Exited with code: null

### ISSUE THREAD

**Issue by rishabhmodi03** [adulalhy/Nana-MD#2]
i run bot on my aws instance but it exit with code null in a few hours like 2 hr or 3 hr
and there is not any issue of ram i have 500 mb free ram after running bot

**Comment by adulalhy** [comment]
Yeah i don't know,  because balieys-md always error if ram under 500 mb

**Comment by rishabhmodi03** [comment]
Mine vps has 2gb ram.
It gives error in that also.
